# Generated by Django 4.0.2 on 2022-04-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('batteryCapacity', models.CharField(default='', max_length=255)),
                ('warrantyDuration', models.CharField(default='', max_length=255)),
                ('warrantyType', models.CharField(default='', max_length=255)),
                ('screenSize', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('mobiledevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mobiledivice.mobiledevice')),
                ('laptopType', models.CharField(default='', max_length=255)),
                ('storageType', models.CharField(default='', max_length=255)),
                ('weight', models.CharField(default='', max_length=255)),
            ],
            bases=('mobiledivice.mobiledevice',),
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('mobiledevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mobiledivice.mobiledevice')),
                ('processorType', models.CharField(max_length=255)),
                ('storageCapacity', models.CharField(max_length=255)),
                ('mobileCableType', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
            ],
            bases=('mobiledivice.mobiledevice',),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('mobiledevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mobiledivice.mobiledevice')),
                ('eReader', models.BooleanField(default=False)),
                ('storageCapacity', models.CharField(max_length=255)),
            ],
            bases=('mobiledivice.mobiledevice',),
        ),
    ]
